name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

defaults:
  shell: bash
  working-directory: ./web

jobs:
  test:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        name: 'Checkout repository'

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Run tests'
        run: npm run test
  
  lint:
    name: 'Run linter'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        name: 'Checkout repository'

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Run linter'
        run: npm run lint

